### ISSUE TITLE
PRs needed: browserify-shim

### ISSUE THREAD

**Issue by bendrucker** [open-sorcery/discuss#2]
https://github.com/thlorenz/browserify-shim
http://npm-stat.com/charts.html?package=browserify-shim&author=&from=&to=

* Gets 125k downloads a month
* browserify gets 1.7m

So it's quite popular. Could really use PRs to clean it up.

It's a critical tool if you want to use browserify w/ a lot of jQuery/Angular plugins (not written in common JS) so it gets plenty of use. I'll likely need it at Eaze. The end goal is to ultimately move off the shim via a PR to the non-CJS libs a la what we did with Angular:

http://angularjs.blogspot.com/2015/02/new-angularjs-releases-140-beta5-and.html
https://github.com/angular/angular.js/pull/10732

The Webpack solution to this sucks (http://webpack.github.io/docs/shimming-modules.html).

**Comment by bendrucker** [comment]
ping @open-sorcery/owners -- if you want notifications make sure to watch the repo

**Comment by chinedufn** [comment]
Hmm, why not skip the shim step entirely? 

1. fork
2. CJS
3. Depend on your fork
4. Submit PR
5. Depend on upstream

Ideally b-shim will become less and less necessary over time.

**Comment by bendrucker** [comment]
Submitting a PR isn't always so easy and you don't want to maintain a fork for an extended period of time and miss out on bug fixes / have to merge them in yourself. So yes the goal is eliminating b-shim in time, but the process isn't as easy as you're anticipating.

**Comment by chinedufn** [comment]
I might be mistaken, but it sounds like you're advocating for cleaning up a tool that:

1. will hopefully become less and less useful in the coming months
2. already works as intended

I can see an appeal for ripping out and releasing useful/interesting bits of the internals.. But I'd rather see us 'cleaning up' things that we expect to have a longer shelf life.

> It's a critical tool if you want to use browserify w/ a lot of jQuery/Angular plugins (not written in common JS)

Hmm, have a few examples in mind of packages that you might/will use that don't have good CJS alternatives. 

---

I'm not (currently) personally invested in this issue since all of my deps have gone CJS over the last couple of months. Just curious about exactly what you have in mind here.

**Comment by bendrucker** [comment]
> already works as intended

**Comment by chinedufn** [comment]
Hmm, I tip my hat to anyone that can find interesting problems by sifting through packages that they don't use or care for. Sounds unpleasantly inorganic. 
I've found more fun in contributing to things that I'm passionate about.

Aside from this... :

I don't like the subtle (possibly unintended) implications of this issue.

I think that our discussions should be focused solely on interesting projects, topics and problems. I'd tread carefully with implying that more popular packages are more deserving of PR's. Sends the wrong message about open-source contributions.

IMO this org and our meetings should encourage contributions of all sizes, and not start to glorify work on larger projects.

**Comment by bendrucker** [comment]
> more popular packages are more deserving of PRs

In the right circumstances they are. You want to get maximum leverage out of your time. 

https://github.com/thlorenz/browserify-shim/blob/master/test/bundle-deps.js

There's a bunch of interesting strategies around writing browserify transforms that are worth understanding. At very least b-shim is a worthwhile read. I'll leave it at that.
